# Generated by Django 3.1.3 on 2020-11-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20201123_1846'),
        ('blogging', '0005_auto_20201123_0354'),
    ]

    operations = [
    ]
